In [1]:
import pandas as pd
dataset1=pd.read_csv('bdp.csv')
dataset1.head()

Sl. No.  Pulse  Systolic Pressure  Diastolic Pressure
0        1     73                128                  78
1        2     71                127                  73
2        3     71                129                  78
3        4     68                125                  69
4        5     68                125                  72

In [2]:
dataset1.isnull().sum()

Sl. No.               0
Pulse                 0
Systolic Pressure     0
Diastolic Pressure    0
dtype: int64

In [3]:
dataset1=dataset1.dropna(axis=1)
dataset1.head()

Sl. No.  Pulse  Systolic Pressure  Diastolic Pressure
0        1     73                128                  78
1        2     71                127                  73
2        3     71                129                  78
3        4     68                125                  69
4        5     68                125                  72

In [4]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sl. No.             150 non-null    int64
 1   Pulse               150 non-null    int64
 2   Systolic Pressure   150 non-null    int64
 3   Diastolic Pressure  150 non-null    int64
dtypes: int64(4)
memory usage: 4.8 KB


In [5]:
dataset1.describe()

Sl. No.       Pulse  Systolic Pressure  Diastolic Pressure
count  150.000000  150.000000         150.000000          150.000000
mean    75.500000   75.153333         124.406667           76.533333
std     43.445368    5.994110           4.000162            5.288542
min      1.000000   66.000000         109.000000           67.000000
25%     38.250000   71.000000         122.000000           73.000000
50%     75.500000   73.000000         125.000000           76.000000
75%    112.750000   78.750000         127.000000           79.750000
max    150.000000   93.000000         134.000000           92.000000

In [6]:
df=dataset1.drop(['Sl. No.'],axis=1)
df.head()

Pulse  Systolic Pressure  Diastolic Pressure
0     73                128                  78
1     71                127                  73
2     71                129                  78
3     68                125                  69
4     68                125                  72

In [7]:
x=df.iloc[:,:1]  #pulse
y=df.iloc[:,-1]  #diastolic
z=df.iloc[:,-2]  #systolic
z.head()

0    128
1    127
2    129
3    125
4    125
Name: Systolic Pressure, dtype: int64

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
l_train,l_test,r_train,r_test=train_test_split(x,y,test_size=0.2,random_state=0)
lr=LinearRegression()
lr.fit(l_train,r_train)

LinearRegression()

In [9]:
lr.predict(l_train)

array([75.97430293, 74.44271278, 76.58693899, 78.42484717, 74.44271278,
       76.89325702, 75.6679849 , 74.44271278, 74.44271278, 75.36166687,
       75.97430293, 75.36166687, 78.11852914, 75.6679849 , 75.97430293,
       75.6679849 , 78.11852914, 78.42484717, 77.50589308, 76.28062096,
       75.6679849 , 79.34380126, 75.6679849 , 77.19957505, 75.97430293,
       78.7311652 , 76.58693899, 77.50589308, 74.44271278, 75.6679849 ,
       75.05534884, 76.89325702, 76.89325702, 75.6679849 , 75.05534884,
       78.11852914, 75.36166687, 75.05534884, 79.34380126, 75.05534884,
       75.97430293, 75.97430293, 80.56907339, 75.36166687, 75.36166687,
       74.44271278, 78.7311652 , 74.74903081, 75.36166687, 75.97430293,
       75.6679849 , 77.19957505, 76.28062096, 75.6679849 , 74.44271278,
       74.74903081, 77.81221111, 77.19957505, 74.44271278, 75.36166687,
       77.19957505, 80.56907339, 75.36166687, 75.36166687, 76.89325702,
       76.58693899, 75.05534884, 74.44271278, 78.7311652 , 76.89

In [10]:
y1=df.iloc[:,1:3] #target
x1=df.iloc[:,:-2] #features
y1.head() 

Systolic Pressure  Diastolic Pressure
0                128                  78
1                127                  73
2                129                  78
3                125                  69
4                125                  72

In [11]:
x1.head()

Pulse
0     73
1     71
2     71
3     68
4     68

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.2,random_state=0)

In [13]:
lr.fit(x_train,y_train) #training the model

LinearRegression()

In [14]:
pred1=lr.predict(x_test) #TESTING THE MODEL
pred1

array([[124.85296044,  77.19957505],
       [123.79992588,  74.74903081],
       [123.53666724,  74.13639474],
       [123.53666724,  74.13639474],
       [123.79992588,  74.74903081],
       [124.72133112,  76.89325702],
       [126.5641416 ,  81.18170945],
       [125.37947772,  78.42484717],
       [125.64273636,  79.03748323],
       [125.905995  ,  79.65011929],
       [125.64273636,  79.03748323],
       [124.85296044,  77.19957505],
       [126.03762432,  79.95643732],
       [124.45807248,  76.28062096],
       [123.79992588,  74.74903081],
       [124.5897018 ,  76.58693899],
       [125.2478484 ,  78.11852914],
       [124.19481384,  75.6679849 ],
       [125.37947772,  78.42484717],
       [123.79992588,  74.74903081],
       [123.79992588,  74.74903081],
       [124.19481384,  75.6679849 ],
       [125.51110704,  78.7311652 ],
       [124.19481384,  75.6679849 ],
       [124.98458976,  77.50589308],
       [126.03762432,  79.95643732],
       [123.66829656,  74.44271278],
 

In [15]:
n=int(input())
x=[[n]]
pred=lr.predict(x)
pred

72


C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[124.19481384,  75.6679849 ]])

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
import numpy as np
rmse=np.sqrt(mean_squared_error(y_test,pred1))
rmse

4.610966686236843

In [18]:
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor(n_estimators=100,random_state=42)
reg.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [19]:
pred2=reg.predict(x_test) #TESTING THE MODEL
pred2

array([[126.86288004,  73.34566131],
       [125.32145238,  76.14511508],
       [124.03491071,  87.51510714],
       [124.03491071,  87.51510714],
       [125.32145238,  76.14511508],
       [124.72338799,  75.65539992],
       [128.52666667,  81.16666667],
       [126.30416667,  76.12266667],
       [125.99811111,  77.74822222],
       [129.98703175,  76.89381746],
       [125.99811111,  77.74822222],
       [126.86288004,  73.34566131],
       [130.796     ,  80.3155    ],
       [123.35701587,  74.94696825],
       [125.32145238,  76.14511508],
       [122.53112698,  76.4625754 ],
       [124.04855478,  80.90912138],
       [123.73366196,  75.22883425],
       [126.30416667,  76.12266667],
       [125.32145238,  76.14511508],
       [125.32145238,  76.14511508],
       [123.73366196,  75.22883425],
       [119.35319048,  84.02892857],
       [123.73366196,  75.22883425],
       [126.59188889,  72.13849206],
       [130.796     ,  80.3155    ],
       [122.62508779,  73.70099386],
 

In [20]:
rmse=np.sqrt(mean_squared_error(y_test,pred2))
rmse

5.967580477088451

In [ ]:
n=int(input())
x=[[n]]
pred=reg.predict(x)
pred